version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - db

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nationalpark
      POSTGRES_DB: nationalpark
      HOST: 'db'
      PORT: '5432'

volumes:
  postgres_data:
